### ISSUE TITLE
OctoKit not found exception

### ISSUE THREAD

**Issue by optimumtact** [Cyberboss/MapDiffBot#48]
An error occurred during the operation:

Octokit.NotFoundException: Not Found
   at Octokit.Connection.HandleErrors(IResponse response) in S:\Documents\Actual Documents\DA Git\octokit.net\Octokit\Http\Connection.cs:line 665
   at Octokit.Connection.<RunRequest>d__58.MoveNext() in S:\Documents\Actual Documents\DA Git\octokit.net\Octokit\Http\Connection.cs:line 642
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__57`1.MoveNext() in S:\Documents\Actual Documents\DA Git\octokit.net\Octokit\Http\Connection.cs:line 626
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.GitHubManager.<GetPullRequest>d__15.MoveNext() in /src/MapDiffBot/GitHubManager.cs:line 272
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<ScanPullRequest>d__13.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 155
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}

https://github.com/tgstation/tgstation/pull/37568

**Comment by Cyberboss** [comment]
Rebooted the server, docker didn't reconnect the SMB share, mass hysteria
